name: Feature Request
description: Suggest an idea for OpenTruss
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear description of any alternative solutions or features you've considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - Database Schema
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would require breaking changes
          required: false

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        As a [type of user], I want to [action] so that [benefit].
        
        Example:
        As a data engineer, I want to batch import elements so that I can efficiently process large datasets.
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups or screenshots to illustrate your idea
      placeholder: Add mockups or screenshots here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false

